### ISSUE TITLE
Error 404 after installation

### ISSUE THREAD

**Issue by igorxmath** [linuxserver/docker-xbackbone#11]
i'm getting a 404 error after installing xbackbone (3.16) in raspberrypi (arm64) on UBUNTU OS

**Comment by ghost** [comment]
I am also having this problem
The error is "No webpage was found for the web address: webaddress.com/home"

**Comment by j0nnymoe** [comment]
This issue is invalid until the original poster provides the information that is requested in the template when opening.

**Comment by Freekers** [comment]
I'm experiencing the same issue. I filed a new bug report using the provided template. https://github.com/linuxserver/docker-xbackbone/issues/12

Thanks

**Comment by j0nnymoe** [comment]
@Freekers thank you, I'll close this issue and we will continue in the other thread.
