### ISSUE TITLE
Cannot set PHP_UPLOAD_MAX_FILESIZE

### ISSUE THREAD

**Issue by jeprecated** [linuxserver/docker-xbackbone#19]
## Expected Behavior

I wish to increase the environment variable `PHP_UPLOAD_MAX_FILESIZE`. This is the keys name in the original docker image. I see no way to set it here. I have tried `PHP_UPLOAD_MAX_FILESIZE` and `UPLOAD_MAX_FILESIZE` to no avail.

## Current Behavior

No environment variable is documented.

## Environment
**OS:** Unraid
**CPU architecture:** Intel? idk
**How docker service was installed:** Via the Unraid App Store, and therefore through DockerHub

**Comment by jeprecated** [comment]
https://xbackbone.app/common_issues.html

**Comment by GilbN** [comment]
> ## Expected Behavior
> I wish to increase the environment variable `PHP_UPLOAD_MAX_FILESIZE`. This is the keys name in the original docker image. I see no way to set it here. I have tried `PHP_UPLOAD_MAX_FILESIZE` and `UPLOAD_MAX_FILESIZE` to no avail.
> 
> ## Current Behavior
> No environment variable is documented.
> 
> ## Environment
> **OS:** Unraid **CPU architecture:** Intel? idk **How docker service was installed:** Via the Unraid App Store, and therefore through DockerHub

Read our docs.

**Comment by jeprecated** [comment]
Ah shoot. Could have sworn I did. I must have gotten tabs mixed up then. Apologies!
