### ISSUE TITLE
[BUG] Update from image 3.6.0 to 3.6.1 broke LDAP function

### ISSUE THREAD

**Issue by Hobbabobba** [linuxserver/docker-xbackbone#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the update to the new image Login (LDAP) does not work anymore. xBackBone shows me the error message "wrong credentials". Downgrade to 3.6.0 fixed it.

### Expected Behavior

Login against LDAP should work in 3.6.1 again

### Steps To Reproduce

see `docker-compose.yml` file

### Environment

```markdown
- OS: Ubuntu 20.04
- How docker service was installed: docker-compose.yml
```

### CPU architecture

arm64

### Docker creation

```bash
xbackbone:
    image: linuxserver/xbackbone:version-3.6.1
    container_name: xbackbone
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Berlin
    volumes:
      - /home/ubuntu/docker/xbackbone:/config
    ports:
      - 4481:80
      - 4482:443
    restart: always
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1001
User GID:    1001
───────────────────────────────────────
using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2022-10-04 │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
│ 2022-08-16 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by thespad** [comment]
Looking through the [changelog for 3.6.1](https://github.com/SergiX44/XBackBone/compare/3.6.0...3.6.1) I can't find anything LDAP related that would have caused our image to break.

From our perspective we bumped the base image to [Alpine 3.17](https://github.com/linuxserver/docker-xbackbone/compare/3.6.0-ls69...3.6.1-ls89) so if your LDAP server connection was over TLS with crappy ciphers the openssl v3 bump will likely have broken it, but beyond that we've changed very little.

**Comment by Hobbabobba** [comment]
Thanks for the reply. I use LDAP without encryption.Am 04.05.2023 20:04 schrieb Adam ***@***.***>:
Looking through the changelog for 3.6.1 I can't find anything LDAP related that would have caused our image to break.
From our perspective we bumped the base image to Alpine 3.17 so if your LDAP server connection was over TLS with crappy ciphers the openssl v3 bump will likely have broken it, but beyond that we've changed very little.

**Comment by thespad** [comment]
Do `3.6.1-ls70` and `3.6.1-ls89` both exhibit the same behaviour?

**Comment by Hobbabobba** [comment]
`linuxserver/xbackbone:3.6.1-ls70` is working
`linuxserver/xbackbone:3.6.1-ls89` is not working

**Comment by thespad** [comment]
Ok please try `3.6.1-ls75` and `3.6.1-ls76`m I suspect it's the bump to Alpine 3.17 and php 8.1 that's causing you the issue.

**Comment by Hobbabobba** [comment]
`3.6.1-ls75` is working
`3.6.1-ls76` is not working

**Comment by thespad** [comment]
Yes, the `m` was a typo. OK so it's something in the Alpine 3.17 bump, *probably* something PHP 8.1-related as you're not using TLS.

I would raise this as an issue with the upstream repo, provide the necessary information regarding PHP versions, etc. and see if there are any known issues. We can change things around if required, but without some idea of where the issue might lie we'd just be doing things at random.

**Comment by Hobbabobba** [comment]
just a guess: is the `php-ldap` extension installed in the latest container?
