### ISSUE TITLE
Unable to view or download file stored in S3 compatible storage

### ISSUE THREAD

**Issue by MrSuttonmann** [linuxserver/docker-xbackbone#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a file is uploaded to an S3 compatible storage, the file is unable to be viewed or downloaded.

The thumbnail displays correctly:

![image](https://github.com/linuxserver/docker-xbackbone/assets/7480500/bd764517-111c-4709-8a79-9a0f15a871c5)

However, when clicking View, the file does not load:

![image](https://github.com/linuxserver/docker-xbackbone/assets/7480500/437197ca-fbf9-423e-9a50-639ce1538aef)

### Expected Behavior

The file should be able to be viewed and downloaded.

### Steps To Reproduce

1. Set up S3 compatible storage (in my case Scaleway).
2. Upload a file
3. Attempt to view or download the file.

### Environment

```markdown
- OS: Debian 12
- How docker service was installed: packagemanager
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  xbackbone:
    image: lscr.io/linuxserver/xbackbone:latest
    container_name: xbackbone
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/james/docker/xbackbone:/config
    ports:
      - 2100:80
      - 21443:443
    restart: unless-stopped
networks: {}
```

### Container logs

```bash
xbackbone  | [migrations] started
xbackbone  | [migrations] 01-nginx-site-confs-default: skipped
xbackbone  | [migrations] done
xbackbone  | usermod: no changes
xbackbone  | ───────────────────────────────────────
xbackbone  | 
xbackbone  |       ██╗     ███████╗██╗ ██████╗ 
xbackbone  |       ██║     ██╔════╝██║██╔═══██╗
xbackbone  |       ██║     ███████╗██║██║   ██║
xbackbone  |       ██║     ╚════██║██║██║   ██║
xbackbone  |       ███████╗███████║██║╚██████╔╝
xbackbone  |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
xbackbone  | 
xbackbone  |    Brought to you by linuxserver.io
xbackbone  | ───────────────────────────────────────
xbackbone  | 
xbackbone  | To support LSIO projects visit:
xbackbone  | https://www.linuxserver.io/donate/
xbackbone  | 
xbackbone  | ───────────────────────────────────────
xbackbone  | GID/UID
xbackbone  | ───────────────────────────────────────
xbackbone  | 
xbackbone  | User UID:    1000
xbackbone  | User GID:    1000
xbackbone  | ───────────────────────────────────────
xbackbone  | 
xbackbone  | using keys found in /config/keys
xbackbone  | [custom-init] No custom files found, skipping...
xbackbone  | [ls.io-init] done.
```

**Comment by MrSuttonmann** [comment]
Please also see https://github.com/sergix44/XBackBone/issues/543 and https://github.com/sergix44/XBackBone/issues/536

**Comment by j0nnymoe** [comment]
If they're having issues upstream, it's outside of our control.
