### ISSUE TITLE
[BUG] Upload doesn't seem to work

### ISSUE THREAD

**Issue by jokob-sk** [linuxserver/docker-xbackbone#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When uploading an image via the interface or via the API (via Screencloud) an exception is shown and image is not uploaded. Seems to have worked fine before the latest update as far as I remember. Using Firefox. Couldn't find any logs in the container logs in Portainer. 
![Screenshot at 19-51-33](https://github.com/linuxserver/docker-xbackbone/assets/96159884/5faba891-1013-4ad8-b951-22acb242ca4c)
![Capture](https://github.com/linuxserver/docker-xbackbone/assets/96159884/9b43043e-2ae0-4b34-9a1a-184ef45e4d3a)

EDIT: Tested [3.7.0-ls149](https://hub.docker.com/layers/linuxserver/xbackbone/3.7.0-ls149/images/sha256-63b234b090685f2c0dcff032fe170966a134bae5d48b06aa68e64001244488bb?context=explore) which works fine

### Expected Behavior

Fiel is uplaoded

### Steps To Reproduce

1. Using Firefox or the API
2. Uploading image fails

### Environment

```markdown
- OS:Synology
- How docker service was installed: docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3"
services:
  xbackbone:
    container_name: xbackbone
    image: lscr.io/linuxserver/xbackbone:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_LOCATION}/xbackbone/data:/config
    environment:
      - TZ=Australia/Sydney
      - PUID=1036
      - PGID=1000
    ports:
      - 36780:80
      - 36743:443
```

### Container logs

```bash
[migrations] started

[migrations] 01-nginx-site-confs-default: skipped

[migrations] done

───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗

      ██║     ██╔════╝██║██╔═══██╗

      ██║     ███████╗██║██║   ██║

      ██║     ╚════██║██║██║   ██║

      ███████╗███████║██║╚██████╔╝

      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io

───────────────────────────────────────

To support LSIO projects visit:

https://www.linuxserver.io/donate/

───────────────────────────────────────

GID/UID

───────────────────────────────────────

User UID:    1036

User GID:    1000

───────────────────────────────────────

Linuxserver.io version: 3.7.0-ls152

Build-date: 2024-06-02T02:36:57+00:00

───────────────────────────────────────

    

using keys found in /config/keys

**** The following active confs have different version dates than the samples that are shipped. ****

**** This may be due to user customization or an update to the samples. ****

**** You should compare the following files to the samples in the same folder and update them. ****

**** Use the link at the top of the file to view the changelog. ****

┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐

│  old date  │  new date  │ path                                                                   │

├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤

│ 2023-04-13 │ 2024-05-27 │ /config/nginx/nginx.conf                                               │

│ 2023-04-13 │ 2024-05-27 │ /config/nginx/site-confs/default.conf                                  │

└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘

[custom-init] No custom files found, skipping...

[ls.io-init] done.

nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:7

nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:8
```
```

**Comment by thespad** [comment]
Just updated to the latest image and tested an upload with Firefox, seems to be working fine. Check the nginx access and error logs for anything that stands out, and you can also check /config/www/xbackbone/logs/ for application logs.

**Comment by jokob-sk** [comment]
Thanks, redownloaded the latest image and it seems to be working, maybe it was the [amd64-3.7.0-ls151](https://hub.docker.com/layers/linuxserver/xbackbone/amd64-3.7.0-ls151/images/sha256-0a9dd0219e1699af8e995b2041e9ec44eadc150027dadf36460692484a9159d5?context=explore), thanks for the check and reply!
