### ISSUE TITLE
sorting is not working

### ISSUE THREAD

**Issue by darkzero-sdz** [linuxserver/docker-xbackbone#8]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

sorting of images via tags/size/name
## Current Behavior

page reloads, but nothing changes
## Steps to Reproduce

1.install this docker image on Synology via Portainer or Script
2.upload some images, give them tags
3.try to sort these images
4.nothing changes

## Environment
**OS:** DSM7
**CPU architecture:** arm64
**How docker service was installed:**
 from portainer (docker compose) or  via synology tasks (cli)

## Docker logs

no error messages in logs

**Comment by GilbN** [comment]
Hi. This sounds like an application issue. Please make an issue on the xbackbone repo https://github.com/SergiX44/XBackBone/issues

**Comment by JohnFawkes** [comment]
This isnt an app issue. its actually an issue here. the default file needs the line 

location / {
    try_files $uri $uri/ /index.php;
}

changed to 

location / {
    try_files $uri $uri/ /index.php?$query_string;
}

**Comment by JohnFawkes** [comment]
its correct in SergiX44s repo but its incorrect here

**Comment by GilbN** [comment]
> its correct in SergiX44s repo but its incorrect here

Thanks for letting us know. Merged your PR

**Comment by JohnFawkes** [comment]
> > its correct in SergiX44s repo but its incorrect here
> 
> Thanks for letting us know. Merged your PR

Awesome! thanks!

**Comment by Sloth-on-meth** [comment]
this issue is still occuring for me

**Comment by nemchik** [comment]
To the user who commented (which triggered an email notification):

If you're still having an issue, please open a new issue and fill out the issue template. A quick suspected fix to your issue may be to check your container logs (`docker logs xbackbone`) and review the log message about outdated configs and update your configs accordingly.

**Comment by Sloth-on-meth** [comment]
Apologies - the fix was to delete the nginx siteconf and pull the container again.
